const express = require('express');
const cors = require('cors');
const { GoogleGenerativeAI } = require("@google/generative-ai");
const sqlParser = require('sql-parser'); 
require('dotenv').config();

const app = express();
app.use(cors()); // Allows your React app to talk to this API
app.use(express.json());

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// SECURITY: The Validator
const isSqlSafe = (sql) => {
    try {
        // Remove any markdown formatting if AI included it
        const cleanSql = sql.replace(/```sql|```/g, "").trim();
        const tokens = sqlParser.lexer.tokenize(cleanSql);
        const firstToken = tokens[0][0];
        
        // 1. Only allow SELECT (Read-only)
        if (firstToken !== 'SELECT') return { safe: false, msg: "Permission Denied: Only SELECT queries are allowed." };
        
        // 2. Block destructive keywords
        const dangerous = ['DROP', 'DELETE', 'UPDATE', 'INSERT', 'ALTER', 'TRUNCATE'];
        if (tokens.some(t => dangerous.includes(t[1].toUpperCase()))) {
            return { safe: false, msg: "Security Alert: Destructive command detected." };
        }
        
        return { safe: true, cleanSql };
    } catch (e) {
        return { safe: false, msg: "Invalid SQL Syntax generated by AI." };
    }
};

app.post('/generate-sql', async (req, res) => {
    try {
        const { prompt } = req.body;
        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

        const aiPrompt = `You are a SQL expert. Convert this to SQL: "${prompt}". 
        Schema: Users(id, name, email, join_date). 
        Output ONLY the raw SQL string. Do not use markdown blocks.`;

        const result = await model.generateContent(aiPrompt);
        const response = await result.response;
        let rawSql = response.text();

        // 🛠️ CLEANUP: Remove ```sql and ``` if the AI adds them anyway
        rawSql = rawSql.replace(/```sql/ig, '').replace(/```/g, '').trim();

        console.log("🤖 AI Generated:", rawSql);

        const check = isSqlSafe(rawSql);
        
        if (check.safe) {
            res.json({ sql: check.cleanSql, safe: true });
        } else {
            res.status(403).json({ error: check.msg, safe: false });
        }
    } catch (error) {
        console.error("❌ ERROR:", error);
        res.status(500).json({ error: error.message });
    }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`🚀 Backend running on http://localhost:${PORT}`));